# handlers/states.py
import keyboards
import database
import config
# --- Definisi State ---
ROUTE = chr(0)

# SSH
SSH_GET_USERNAME, SSH_GET_PASSWORD, SSH_GET_DURATION, SSH_GET_IP_LIMIT = map(chr, range(1, 5))
RENEW_SSH_GET_USERNAME, RENEW_SSH_GET_DURATION = map(chr, range(15, 17))
SSH_SELECT_ACCOUNT = chr(26)

# VMESS
VMESS_GET_USER, VMESS_GET_DURATION = map(chr, range(5, 7))
VMESS_SELECT_ACCOUNT = chr(25)
RENEW_VMESS_GET_USERNAME, RENEW_VMESS_GET_DURATION = map(chr, range(27, 29))

# VLESS
VLESS_GET_USER, VLESS_GET_DURATION, VLESS_GET_IP_LIMIT, VLESS_GET_QUOTA = map(chr, range(7, 11))

# TROJAN
TROJAN_GET_USER, TROJAN_GET_DURATION, TROJAN_GET_IP_LIMIT, TROJAN_GET_QUOTA = map(chr, range(11, 15))

# TRIAL
TRIAL_CREATE_SSH, TRIAL_CREATE_VMESS, TRIAL_CREATE_VLESS, TRIAL_CREATE_TROJAN = map(chr, range(18, 22))

# DELETE
DELETE_GET_USERNAME, DELETE_CONFIRMATION = map(chr, range(22, 24))

# AUTHENTICATION
GET_PHONE_NUMBER, GET_OTP = map(chr, range(30, 32))
GET_KMSP_OTP = chr(33)
